dec = int(input("Enter Decimal: \n"))
cha = input('Enter CHARACTER: = \n')
binary = bin(dec)
octal = oct(dec)
hexa = hex(dec)
ASCII = ord(cha)
print('Given decimal number is {}'.format(dec))
print('binary value of decimal number {} is'.format(dec),'= {}'.format(binary))
print('octal value of decimal number {} is'.format(dec),'= {}'.format(octal))
print('Hexadecimal value of decimal number {} is'.format(dec),'= {}'.format(hexa))
print('ASCII value of character {} is'.format(cha),'= {}'.format(ASCII))